### ISSUE TITLE
Player attributes

### ISSUE THREAD

**Issue by Thomas--S** [bell07/minetest-schnitzeljagd#1]
Why aren't you using `player:set_attribute(attribute, value)` and `player:get_attribute(attribute)` for storing the player-related information?

**Comment by bell07** [comment]
Thank you for the hint! The previous version was one chain for all users so I did not realized I can use this. Now the chain is per-player so you are right. Done in https://github.com/bell07/minetest-schnitzeljagd/commit/43d3b99a868157fbe6540e3636002d8b46434fcd
